### ISSUE TITLE
[提案] ノードエディタでストーリを作れるようにする

### ISSUE THREAD

**Issue by elect-gombe** [inajob/cyoa-experiment#2]
ノードエディタでストーリが作れるかもなんて思いました。

マルチプラットフォームなやつではこんなのがあります。
https://github.com/thedmd/imgui-node-editor

ノードで場面を表現し、有向辺で推移を示すとか、どうでしょうか?

**Comment by inajob** [comment]
確かにストーリをテキストエディタ以外で作れるようにすると敷居が下がりそうですね。
ノードエディタが適した可視化方法化は議論の余地がありそうですが、良いアイデアだと思います！

個人的には、もう少しPRなどが飛んできて、この試みに意味があることが検証できてから取り組むのが良いかなと思い今は後回しにしています。（もちろん誰かが作ってくれるなら大歓迎ですがｗ）

**Comment by elect-gombe** [comment]
わかりました。今後も楽しみにしてます。もしかしたら自分で趣味でグラフエディタ作るかも()

**Comment by inajob** [comment]
手元で可視化を試した見たところこんな画像が得られました。
masterにこの機能はまだ入れませんが、どんな感じだろう？というイメージをつかめそうなのでここに共有します

![image](https://user-images.githubusercontent.com/291177/73606584-234d7300-45ef-11ea-88f9-79d842c334c7.png)
